#!/usr/bin/env python
"""Render the expectations-inversion (WS1.1) -> analysis/expectations_inversion.md + viz/expectations.json.

Reads the carded inputs (src/bubble/expectations/names.py), runs both inversions across the
scenario grid (src/bubble/expectations/inversion.py), and writes the human doc + a machine
artifact the explorer can render. Deterministic: re-running with unchanged inputs reproduces
the output byte-for-byte (modulo the as-of stamp, which is carded, not clock-derived).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from bubble.expectations.inversion import (  # noqa: E402
    DISCOUNT_RATES,
    FCF_MARGINS,
    TERMINAL_GROWTH,
    invert_all,
)
from bubble.expectations.names import AS_OF, NAMES  # noqa: E402

DOC = ROOT / "analysis" / "expectations_inversion.md"
JSON_OUT = ROOT / "viz" / "expectations.json"


def _fmt_mult(band: dict[str, float]) -> str:
    if band["low"] == float("inf"):
        return "n/a"
    return f"{band['low']:.1f}x – {band['high']:.1f}x (med {band['median']:.1f}x)"


def _fmt_pct(band: dict[str, float]) -> str:
    if band["low"] == float("inf"):
        return "n/a"
    return f"{band['low'] * 100:.0f}% – {band['high'] * 100:.0f}% (med {band['median'] * 100:.0f}%)"


def render_markdown(results: list[dict]) -> str:
    rates = ", ".join(f"{r:.0%}" for r in DISCOUNT_RATES)
    margins = ", ".join(f"{m:.0%}" for m in FCF_MARGINS)
    lines = [
        "# Expectations inversion — what the price is paying for",
        "",
        f"**As of {AS_OF}.** Companion to [expectations_vs_measured.md](expectations_vs_measured.md). "
        "The engine measures reality; this recovers the *market-implied* model — the second input "
        "to the gap that is the thesis. Generated by `scripts/build_expectations_inversion.py` from "
        "carded inputs (`src/bubble/expectations/names.py`); math in `src/bubble/expectations/"
        "inversion.py`, unit-tested. **Not investment advice.**",
        "",
        "Two stylized inversions, each reported as a **sensitivity band** across a scenario grid "
        f"(discount rates {{{rates}}} × steady-state FCF margins {{{margins}}}; "
        f"terminal growth {TERMINAL_GROWTH:.0%} for the revenue frame):",
        "",
        "1. **Implied revenue multiple** — via a Gordon-growth perpetuity, the perpetual revenue "
        "the EV requires, as a multiple of current revenue. *The price implies revenue must reach "
        "~Nx today's and hold there forever.*",
        "2. **Renewal-dependent share of EV** — the share of EV the *contracted* backlog cannot "
        "justify on its own (PV of backlog-derived FCF over its tenor), which therefore rests on "
        "**re-contracting the assets** after the first term. This is the inversion that bites: a "
        "high share is the market betting GPUs get re-leased at healthy rates after their first "
        "contract — against the engine's ~2–3yr GPU economic life vs 5–7yr debt.",
        "",
        "## The table",
        "",
        "| name | EV | curr. rev (basis) | implied revenue multiple | renewal-dependent share of EV | backlog/yr vs curr. rev |",
        "|---|---|---|---|---|---|",
    ]
    for r in results:
        rev_basis_short = (
            "FY guide"
            if r["ticker"] == "CRWV"
            else ("current ARR" if r["ticker"] in ("NBIS", "IREN") else "Q×4")
        )
        cover = (
            f"{r['annual_backlog_vs_current_revenue_x']:.1f}x"
            if r["annual_backlog_vs_current_revenue_x"] is not None
            else "n/a"
        )
        lines.append(
            f"| **{r['ticker']}** {r['name']} | ${r['ev_usd_b']:.1f}B | "
            f"${r['current_annualized_revenue_usd_b']:.1f}B ({rev_basis_short}) | "
            f"{_fmt_mult(r['implied_revenue_multiple'])} | "
            f"{_fmt_pct(r['renewal_dependent_share'])} | {cover} |"
        )
    lines += [
        "",
        "## Reading it",
        "",
        "- **The revenue multiple is the size of the growth bet.** Even on generous steady-state "
        "margins, the price asks these names to multiply revenue several-fold and hold it in "
        "perpetuity. Where the band's low end is already a large multiple, the optimism is not a "
        "tail scenario — it is the base case the price requires.",
        "- **The renewal-dependent share is the size of the GPU-life bet.** It answers: once the "
        "signed contracts run off, how much of today's price still needs paying? For the GPU "
        "clouds that share is high *and* lands on assets the engine measures at ~2–3yr economic "
        "life — the market is pricing re-lease economics the collateral may not live to deliver.",
        "- **The landlord is not the safe contrast you'd expect.** Even APLD — a data-center "
        "*landlord* with long leases — lands in the same high renewal-dependent band as the GPU "
        "clouds. Under equal FCF margins a 12-year lease spreads rent thin per year and discounts "
        "it heavily, so a long tenor does *not* mechanically cover more of the EV (the model "
        "disproves the intuition). A landlord's true lease margin is higher than this grid assumes, "
        "which would lower its share — carded below as a limitation — but even granting it, ~$11B "
        "of APLD's $16B backlog is CoreWeave, so its backlog quality is only as good as a GPU "
        "cloud's. The recursion doesn't remove the risk; it relocates it.",
        "",
        "## What this does NOT capture (carded, not hidden)",
        "",
        "- Backlog revenue is spread **evenly** over its tenor (real recognition is front- or "
        "back-loaded); capex is **already sunk** into EV via debt; current revenue and near-term "
        "backlog may **double-count**; capacity **option value** is ignored. These are comparative "
        "instruments across names and against the engine's measurements, **not valuations**.",
        "- `current_annualized_revenue` basis **differs per name** (stated in the per-name notes) "
        "because these are mid-ramp businesses; the direction each choice pushes the multiple is "
        "noted so a hostile reader can re-run their own basis.",
        "- **A single FCF-margin grid is applied to all four**, including the landlord (APLD), whose "
        "real lease margin is structurally higher than a GPU cloud's. That uniform grid *overstates* "
        "APLD's renewal-dependent share; a landlord-appropriate margin would lower it. The grid is "
        "kept uniform for comparability and the bias is flagged rather than silently corrected.",
        "- The scenario grid is wide but finite; the published `viz/expectations.json` carries the "
        "full per-name inputs and bands for independent re-computation.",
        "",
        "## Per-name notes & sources",
        "",
    ]
    for r in results:
        lines.append(f"**{r['ticker']} — {r['name']}.** {r['notes']}")
        src = "; ".join(f"[{k}]({v})" for k, v in r["sources"].items())
        lines.append(f"Sources: {src}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    results = invert_all(NAMES)
    DOC.write_text(render_markdown(results))
    JSON_OUT.write_text(
        json.dumps(
            {
                "as_of": AS_OF,
                "scenario_grid": {
                    "discount_rates": list(DISCOUNT_RATES),
                    "fcf_margins": list(FCF_MARGINS),
                    "terminal_growth": TERMINAL_GROWTH,
                },
                "results": results,
            },
            indent=1,
            sort_keys=True,
        )
        + "\n"
    )
    print(f"wrote {DOC.relative_to(ROOT)} + {JSON_OUT.relative_to(ROOT)}: {len(results)} names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
